version: '3.5'

networks:

    app_network:
        name: symfony

services:

    database:
        container_name: symfony-database
        networks:
            - app_network
        image: mariadb
        environment:
            - MYSQL_DATABASE=${SYMFONY_MYSQL_DATABASE:-symfony}
            - MYSQL_ROOT_PASSWORD=${SYMFONY_MYSQL_ROOT_PASSWORD:-root}
            - MYSQL_USER=${SYMFONY_MYSQL_USER:-symfony}
            - MYSQL_PASSWORD=${SYMFONY_MYSQL_PASSWORD:-passwd}
            - MYSQL_ALLOW_EMPTY_PASSWORD=${SYMFONY_MYSQL_EMPTY_PASSWORD:-no}
        volumes:
            - "./symfony/database:/var/lib/mysql"

    webapp:
        image: handmadeapps/symfony
        build:
            context: .
            args:
                ssl: "on"
        depends_on:
            - database
        container_name: symfony-app
        ports:
            - "${SYMFONY_PORT:-8080}:80"
        environment:
            - SYMFONY=${SYMFONY:-myapp}
            - SYMFONY_APP_PUBLIC_FOLDER=${SYMFONY_APP_PUBLIC_FOLDER:-public}
        networks:
            - app_network
        command: apache2-foreground
#        command: bash -c 'bash -s <<EOF
#                  trap "break;exit" SIGHUP SIGINT SIGTERM
#                  while /bin/true; do
#                    su -s "/bin/bash" -c "/usr/local/bin/php /var/www/html/console core:archive" www-data
#                    sleep 3600
#                  done
#                  EOF'
        volumes:
            - "./symfony/www:/var/www"
            - "./symfony/log:/var/log"

    phpmyadmin:
        container_name: symfony-phpmyadmin
        networks:
            - app_network
        image: phpmyadmin/phpmyadmin
        ports:
            - "${PHPMYADMIN_PORT:-9090}:80"
        environment:
            - PMA_HOST=symfony-database




